micronaut.application.name=graalpy-mn-vader-v2
micronaut.router.static-resources.default.enabled=true
micronaut.router.static-resources.default.mapping=/**
micronaut.router.static-resources.default.paths=classpath:public
micronaut.server.multipart.enabled=true
